packages:
  - 'apps/*'
  - 'packages/*'
onlyBuiltDependencies:
  - sharp
  - unrs-resolver
allowBuilds:
  '@nestjs/core': true
  '@prisma/engines': true
  msgpackr-extract: true
  msw: false
  prisma: true
  sharp: true
  unrs-resolver: true
