name = "mcmarket-web"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

[env.production]
route = "example.com/*"
zone_id = ""

[build]
command = "cd apps/web && pnpm run build"
cwd = "./"
watch_paths = ["apps/web/src/**/*"]

[build.upload]
format = "modules"

[compatibility_flags]
nodejs_compat = true

[env.production.compatibility_flags]
nodejs_compat = true

[observability]
enabled = true
